"""Initial migration with all tables

Revision ID: 7e1c0ff90743
Revises: 
Create Date: 2026-06-14 13:04:14.250315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1c0ff90743'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_org_plan_active', 'organizations', ['plan', 'is_active'], unique=False)
    op.create_index('idx_org_slug_active', 'organizations', ['slug', 'is_active'], unique=False)
    op.create_index(op.f('ix_organizations_created_at'), 'organizations', ['created_at'], unique=False)
    op.create_index(op.f('ix_organizations_deleted_at'), 'organizations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_organizations_is_active'), 'organizations', ['is_active'], unique=False)
    op.create_index(op.f('ix_organizations_is_deleted'), 'organizations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_organizations_is_suspended'), 'organizations', ['is_suspended'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_owner_id'), 'organizations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_organizations_plan'), 'organizations', ['plan'], unique=False)
    op.create_index(op.f('ix_organizations_plan_expires_at'), 'organizations', ['plan_expires_at'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_index(op.f('ix_organizations_updated_at'), 'organizations', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_organization', 'users', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email_verified_at'), 'users', ['email_verified_at'], unique=False)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_is_superuser'), 'users', ['is_superuser'], unique=False)
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    op.create_index(op.f('ix_users_last_login_at'), 'users', ['last_login_at'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_keys',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('rate_limit_period', sa.String(length=20), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_key_expires', 'api_keys', ['expires_at', 'is_active'], unique=False)
    op.create_index('idx_api_key_org_active', 'api_keys', ['organization_id', 'is_active'], unique=False)
    op.create_index('idx_api_key_user_active', 'api_keys', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_keys_expires_at'), 'api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_is_revoked'), 'api_keys', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_last_used_at'), 'api_keys', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.create_index(op.f('ix_api_keys_updated_at'), 'api_keys', ['updated_at'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('idx_audit_ip_created', 'audit_logs', ['ip_address', 'created_at'], unique=False)
    op.create_index('idx_audit_org_category', 'audit_logs', ['organization_id', 'category', 'created_at'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_status_created', 'audit_logs', ['status', 'created_at'], unique=False)
    op.create_index('idx_audit_user_action_created', 'audit_logs', ['user_id', 'action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_category'), 'audit_logs', ['category'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_updated_at'), 'audit_logs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('businesses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_business_org_slug')
    )
    op.create_index('idx_business_org_active', 'businesses', ['organization_id', 'is_active'], unique=False)
    op.create_index('idx_business_type_active', 'businesses', ['business_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_businesses_business_type'), 'businesses', ['business_type'], unique=False)
    op.create_index(op.f('ix_businesses_city'), 'businesses', ['city'], unique=False)
    op.create_index(op.f('ix_businesses_country'), 'businesses', ['country'], unique=False)
    op.create_index(op.f('ix_businesses_created_at'), 'businesses', ['created_at'], unique=False)
    op.create_index(op.f('ix_businesses_deleted_at'), 'businesses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_businesses_email'), 'businesses', ['email'], unique=False)
    op.create_index(op.f('ix_businesses_industry'), 'businesses', ['industry'], unique=False)
    op.create_index(op.f('ix_businesses_is_active'), 'businesses', ['is_active'], unique=False)
    op.create_index(op.f('ix_businesses_is_deleted'), 'businesses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_businesses_is_verified'), 'businesses', ['is_verified'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_index(op.f('ix_businesses_organization_id'), 'businesses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_businesses_owner_id'), 'businesses', ['owner_id'], unique=False)
    op.create_index(op.f('ix_businesses_slug'), 'businesses', ['slug'], unique=False)
    op.create_index(op.f('ix_businesses_updated_at'), 'businesses', ['updated_at'], unique=False)
    op.create_table('email_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_email_verifications_expires_at'), 'email_verifications', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_verifications_is_verified'), 'email_verifications', ['is_verified'], unique=False)
    op.create_index(op.f('ix_email_verifications_token_hash'), 'email_verifications', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verifications_user_id'), 'email_verifications', ['user_id'], unique=True)
    op.create_table('login_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_attempted', 'login_attempts', ['email', 'attempted_at'], unique=False)
    op.create_index('idx_ip_attempted', 'login_attempts', ['ip_address', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_attempts_successful'), 'login_attempts', ['successful'], unique=False)
    op.create_index(op.f('ix_login_attempts_user_id'), 'login_attempts', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('push_sent', sa.Boolean(), nullable=False),
    sa.Column('push_sent_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_resource', 'notifications', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_notification_type_created', 'notifications', ['notification_type', 'created_at'], unique=False)
    op.create_index('idx_notification_unread_count', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index('idx_notification_user_priority', 'notifications', ['user_id', 'priority', 'created_at'], unique=False)
    op.create_index('idx_notification_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_deleted_at'), 'notifications', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_notifications_email_sent'), 'notifications', ['email_sent'], unique=False)
    op.create_index(op.f('ix_notifications_expires_at'), 'notifications', ['expires_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_priority'), 'notifications', ['priority'], unique=False)
    op.create_index(op.f('ix_notifications_read_at'), 'notifications', ['read_at'], unique=False)
    op.create_index(op.f('ix_notifications_resource_id'), 'notifications', ['resource_id'], unique=False)
    op.create_index(op.f('ix_notifications_resource_type'), 'notifications', ['resource_type'], unique=False)
    op.create_index(op.f('ix_notifications_updated_at'), 'notifications', ['updated_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_org_member')
    )
    op.create_index('idx_org_member_org_role', 'organization_members', ['organization_id', 'role'], unique=False)
    op.create_index('idx_org_member_user_active', 'organization_members', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_organization_members_created_at'), 'organization_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_members_is_active'), 'organization_members', ['is_active'], unique=False)
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_role'), 'organization_members', ['role'], unique=False)
    op.create_index(op.f('ix_organization_members_updated_at'), 'organization_members', ['updated_at'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('otp_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('code_type', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_user_purpose_active', 'otp_codes', ['user_id', 'purpose', 'is_used', 'is_verified'], unique=False)
    op.create_index(op.f('ix_otp_codes_code_type'), 'otp_codes', ['code_type'], unique=False)
    op.create_index(op.f('ix_otp_codes_expires_at'), 'otp_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_codes_is_used'), 'otp_codes', ['is_used'], unique=False)
    op.create_index(op.f('ix_otp_codes_is_verified'), 'otp_codes', ['is_verified'], unique=False)
    op.create_index(op.f('ix_otp_codes_purpose'), 'otp_codes', ['purpose'], unique=False)
    op.create_index(op.f('ix_otp_codes_user_id'), 'otp_codes', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_is_revoked'), 'password_reset_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_is_used'), 'password_reset_tokens', ['is_used'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_family', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by', sa.String(length=36), nullable=True),
    sa.Column('replaced_by_token', sa.String(length=36), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_token'], ['refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_family_created', 'refresh_tokens', ['token_family', 'created_at'], unique=False)
    op.create_index('idx_user_active_tokens', 'refresh_tokens', ['user_id', 'is_revoked', 'is_used'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_ip_address'), 'refresh_tokens', ['ip_address'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_is_used'), 'refresh_tokens', ['is_used'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_last_used_at'), 'refresh_tokens', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_family'), 'refresh_tokens', ['token_family'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('settings',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'key', name='uq_setting_org_key')
    )
    op.create_index('idx_setting_category', 'settings', ['category', 'organization_id'], unique=False)
    op.create_index(op.f('ix_settings_category'), 'settings', ['category'], unique=False)
    op.create_index(op.f('ix_settings_created_at'), 'settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    op.create_index(op.f('ix_settings_organization_id'), 'settings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_settings_updated_at'), 'settings', ['updated_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=100), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(), nullable=False),
    sa.Column('billing_period_end', sa.DateTime(), nullable=False),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('external_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('external_customer_id', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('last_payment_at', sa.DateTime(), nullable=True),
    sa.Column('next_payment_at', sa.DateTime(), nullable=True),
    sa.Column('failed_payment_attempts', sa.Integer(), nullable=False),
    sa.Column('last_failed_payment_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sub_external', 'subscriptions', ['external_subscription_id', 'external_customer_id'], unique=False)
    op.create_index('idx_sub_next_payment', 'subscriptions', ['next_payment_at', 'status'], unique=False)
    op.create_index('idx_sub_org_status', 'subscriptions', ['organization_id', 'status'], unique=False)
    op.create_index('idx_sub_status_period', 'subscriptions', ['status', 'billing_period_end'], unique=False)
    op.create_index(op.f('ix_subscriptions_billing_cycle'), 'subscriptions', ['billing_cycle'], unique=False)
    op.create_index(op.f('ix_subscriptions_billing_period_end'), 'subscriptions', ['billing_period_end'], unique=False)
    op.create_index(op.f('ix_subscriptions_billing_period_start'), 'subscriptions', ['billing_period_start'], unique=False)
    op.create_index(op.f('ix_subscriptions_cancel_at_period_end'), 'subscriptions', ['cancel_at_period_end'], unique=False)
    op.create_index(op.f('ix_subscriptions_canceled_at'), 'subscriptions', ['canceled_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_external_customer_id'), 'subscriptions', ['external_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_external_subscription_id'), 'subscriptions', ['external_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_last_payment_at'), 'subscriptions', ['last_payment_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_next_payment_at'), 'subscriptions', ['next_payment_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_trial_end'), 'subscriptions', ['trial_end'], unique=False)
    op.create_index(op.f('ix_subscriptions_updated_at'), 'subscriptions', ['updated_at'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_remember', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_expires', 'user_sessions', ['expires_at', 'is_active'], unique=False)
    op.create_index('idx_session_user_active', 'user_sessions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_user_sessions_created_at'), 'user_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_ip_address'), 'user_sessions', ['ip_address'], unique=False)
    op.create_index(op.f('ix_user_sessions_is_active'), 'user_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_sessions_last_active_at'), 'user_sessions', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('business_profiles',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_user_id', sa.String(length=255), nullable=False),
    sa.Column('platform_username', sa.String(length=255), nullable=False),
    sa.Column('platform_profile_url', sa.String(length=500), nullable=True),
    sa.Column('platform_avatar_url', sa.String(length=500), nullable=True),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'platform', 'platform_user_id', name='uq_business_platform_account')
    )
    op.create_index('idx_bp_business_platform', 'business_profiles', ['business_id', 'platform'], unique=False)
    op.create_index('idx_bp_platform_connected', 'business_profiles', ['platform', 'is_connected'], unique=False)
    op.create_index(op.f('ix_business_profiles_business_id'), 'business_profiles', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_profiles_created_at'), 'business_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_business_profiles_is_active'), 'business_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_business_profiles_is_connected'), 'business_profiles', ['is_connected'], unique=False)
    op.create_index(op.f('ix_business_profiles_last_synced_at'), 'business_profiles', ['last_synced_at'], unique=False)
    op.create_index(op.f('ix_business_profiles_platform'), 'business_profiles', ['platform'], unique=False)
    op.create_index(op.f('ix_business_profiles_platform_user_id'), 'business_profiles', ['platform_user_id'], unique=False)
    op.create_index(op.f('ix_business_profiles_platform_username'), 'business_profiles', ['platform_username'], unique=False)
    op.create_index(op.f('ix_business_profiles_token_expires_at'), 'business_profiles', ['token_expires_at'], unique=False)
    op.create_index(op.f('ix_business_profiles_updated_at'), 'business_profiles', ['updated_at'], unique=False)
    op.create_table('leads',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('instagram_user_id', sa.String(length=100), nullable=True),
    sa.Column('instagram_username', sa.String(length=255), nullable=True),
    sa.Column('instagram_profile_url', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('conversation_count', sa.Integer(), nullable=False),
    sa.Column('last_conversation_at', sa.DateTime(), nullable=True),
    sa.Column('funnel_stage', sa.String(length=50), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('converted_to_id', sa.String(length=36), nullable=True),
    sa.Column('converted_to_type', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_assigned_status', 'leads', ['assigned_to', 'status'], unique=False)
    op.create_index('idx_lead_business_status', 'leads', ['business_id', 'status'], unique=False)
    op.create_index('idx_lead_conversion', 'leads', ['funnel_stage', 'converted_at'], unique=False)
    op.create_index('idx_lead_instagram', 'leads', ['instagram_user_id', 'business_id'], unique=False)
    op.create_index('idx_lead_priority_score', 'leads', ['priority', 'score'], unique=False)
    op.create_index(op.f('ix_leads_assigned_to'), 'leads', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_leads_business_id'), 'leads', ['business_id'], unique=False)
    op.create_index(op.f('ix_leads_converted_at'), 'leads', ['converted_at'], unique=False)
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_deleted_at'), 'leads', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_funnel_stage'), 'leads', ['funnel_stage'], unique=False)
    op.create_index(op.f('ix_leads_instagram_user_id'), 'leads', ['instagram_user_id'], unique=False)
    op.create_index(op.f('ix_leads_instagram_username'), 'leads', ['instagram_username'], unique=False)
    op.create_index(op.f('ix_leads_is_deleted'), 'leads', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_leads_last_conversation_at'), 'leads', ['last_conversation_at'], unique=False)
    op.create_index(op.f('ix_leads_name'), 'leads', ['name'], unique=False)
    op.create_index(op.f('ix_leads_priority'), 'leads', ['priority'], unique=False)
    op.create_index(op.f('ix_leads_score'), 'leads', ['score'], unique=False)
    op.create_index(op.f('ix_leads_source_id'), 'leads', ['source_id'], unique=False)
    op.create_index(op.f('ix_leads_source_type'), 'leads', ['source_type'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_updated_at'), 'leads', ['updated_at'], unique=False)
    op.create_table('reports',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('report_format', sa.String(length=20), nullable=False),
    sa.Column('date_range_start', sa.DateTime(), nullable=False),
    sa.Column('date_range_end', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('schedule_frequency', sa.String(length=20), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_report_business_type', 'reports', ['business_id', 'report_type'], unique=False)
    op.create_index('idx_report_date_range', 'reports', ['date_range_start', 'date_range_end'], unique=False)
    op.create_index('idx_report_scheduled_next', 'reports', ['is_scheduled', 'next_run_at'], unique=False)
    op.create_index('idx_report_status_date', 'reports', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_business_id'), 'reports', ['business_id'], unique=False)
    op.create_index(op.f('ix_reports_completed_at'), 'reports', ['completed_at'], unique=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_date_range_end'), 'reports', ['date_range_end'], unique=False)
    op.create_index(op.f('ix_reports_date_range_start'), 'reports', ['date_range_start'], unique=False)
    op.create_index(op.f('ix_reports_deleted_at'), 'reports', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_reports_is_deleted'), 'reports', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_reports_is_scheduled'), 'reports', ['is_scheduled'], unique=False)
    op.create_index(op.f('ix_reports_name'), 'reports', ['name'], unique=False)
    op.create_index(op.f('ix_reports_next_run_at'), 'reports', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_reports_report_format'), 'reports', ['report_format'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_updated_at'), 'reports', ['updated_at'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('resources',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'slug', name='uq_resource_business_slug')
    )
    op.create_index('idx_resource_business_published', 'resources', ['business_id', 'is_published'], unique=False)
    op.create_index('idx_resource_featured', 'resources', ['is_featured', 'is_published'], unique=False)
    op.create_index('idx_resource_type_published', 'resources', ['resource_type', 'is_published'], unique=False)
    op.create_index(op.f('ix_resources_business_id'), 'resources', ['business_id'], unique=False)
    op.create_index(op.f('ix_resources_category'), 'resources', ['category'], unique=False)
    op.create_index(op.f('ix_resources_created_at'), 'resources', ['created_at'], unique=False)
    op.create_index(op.f('ix_resources_deleted_at'), 'resources', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_resources_is_deleted'), 'resources', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_resources_is_featured'), 'resources', ['is_featured'], unique=False)
    op.create_index(op.f('ix_resources_is_premium'), 'resources', ['is_premium'], unique=False)
    op.create_index(op.f('ix_resources_is_published'), 'resources', ['is_published'], unique=False)
    op.create_index(op.f('ix_resources_published_at'), 'resources', ['published_at'], unique=False)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resources_slug'), 'resources', ['slug'], unique=False)
    op.create_index(op.f('ix_resources_title'), 'resources', ['title'], unique=False)
    op.create_index(op.f('ix_resources_updated_at'), 'resources', ['updated_at'], unique=False)
    op.create_table('instagram_accounts',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('business_profile_id', sa.String(length=36), nullable=True),
    sa.Column('instagram_user_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=True),
    sa.Column('is_business', sa.Boolean(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'instagram_user_id', name='uq_instagram_business_user')
    )
    op.create_index('idx_ig_account_business_active', 'instagram_accounts', ['business_id', 'is_active'], unique=False)
    op.create_index('idx_ig_account_username', 'instagram_accounts', ['username', 'is_connected'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_business_id'), 'instagram_accounts', ['business_id'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_business_profile_id'), 'instagram_accounts', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_created_at'), 'instagram_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_deleted_at'), 'instagram_accounts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_instagram_user_id'), 'instagram_accounts', ['instagram_user_id'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_is_active'), 'instagram_accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_is_business'), 'instagram_accounts', ['is_business'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_is_connected'), 'instagram_accounts', ['is_connected'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_is_deleted'), 'instagram_accounts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_last_activity_at'), 'instagram_accounts', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_last_synced_at'), 'instagram_accounts', ['last_synced_at'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_token_expires_at'), 'instagram_accounts', ['token_expires_at'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_updated_at'), 'instagram_accounts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_username'), 'instagram_accounts', ['username'], unique=False)
    op.create_table('comments',
    sa.Column('instagram_account_id', sa.String(length=36), nullable=True),
    sa.Column('business_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('instagram_comment_id', sa.String(length=100), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author_instagram_id', sa.String(length=100), nullable=True),
    sa.Column('author_username', sa.String(length=255), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_reply', sa.Boolean(), nullable=False),
    sa.Column('is_spam', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('auto_reply_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_reply_text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comment_instagram_parent', 'comments', ['instagram_account_id', 'parent_id'], unique=False)
    op.create_index('idx_comment_spam', 'comments', ['is_spam', 'is_hidden'], unique=False)
    op.create_index('idx_comment_timestamp', 'comments', ['timestamp'], unique=False)
    op.create_index(op.f('ix_comments_author_instagram_id'), 'comments', ['author_instagram_id'], unique=False)
    op.create_index(op.f('ix_comments_author_username'), 'comments', ['author_username'], unique=False)
    op.create_index(op.f('ix_comments_business_id'), 'comments', ['business_id'], unique=False)
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_deleted_at'), 'comments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_comments_instagram_account_id'), 'comments', ['instagram_account_id'], unique=False)
    op.create_index(op.f('ix_comments_instagram_comment_id'), 'comments', ['instagram_comment_id'], unique=False)
    op.create_index(op.f('ix_comments_is_deleted'), 'comments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_comments_is_hidden'), 'comments', ['is_hidden'], unique=False)
    op.create_index(op.f('ix_comments_is_reply'), 'comments', ['is_reply'], unique=False)
    op.create_index(op.f('ix_comments_is_spam'), 'comments', ['is_spam'], unique=False)
    op.create_index(op.f('ix_comments_parent_id'), 'comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_comments_sentiment_score'), 'comments', ['sentiment_score'], unique=False)
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.create_index(op.f('ix_comments_updated_at'), 'comments', ['updated_at'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('instagram_account_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('participant_instagram_id', sa.String(length=100), nullable=False),
    sa.Column('participant_username', sa.String(length=255), nullable=False),
    sa.Column('participant_name', sa.String(length=255), nullable=True),
    sa.Column('participant_avatar_url', sa.String(length=500), nullable=True),
    sa.Column('last_message_text', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('messages_count', sa.Integer(), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('is_spam', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('lead_status', sa.String(length=50), nullable=False),
    sa.Column('lead_priority', sa.String(length=50), nullable=False),
    sa.Column('lead_assigned_to', sa.String(length=36), nullable=True),
    sa.Column('lead_tags', sa.JSON(), nullable=False),
    sa.Column('lead_notes', sa.Text(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instagram_account_id', 'participant_instagram_id', name='uq_conversation_participant'),
    sa.UniqueConstraint('instagram_account_id', 'thread_id', name='uq_conversation_thread')
    )
    op.create_index('idx_conv_account_status', 'conversations', ['instagram_account_id', 'lead_status'], unique=False)
    op.create_index('idx_conv_assigned_priority', 'conversations', ['lead_assigned_to', 'lead_priority'], unique=False)
    op.create_index('idx_conv_last_message', 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_deleted_at'), 'conversations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_conversations_instagram_account_id'), 'conversations', ['instagram_account_id'], unique=False)
    op.create_index(op.f('ix_conversations_is_archived'), 'conversations', ['is_archived'], unique=False)
    op.create_index(op.f('ix_conversations_is_deleted'), 'conversations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_conversations_is_spam'), 'conversations', ['is_spam'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_lead_assigned_to'), 'conversations', ['lead_assigned_to'], unique=False)
    op.create_index(op.f('ix_conversations_lead_priority'), 'conversations', ['lead_priority'], unique=False)
    op.create_index(op.f('ix_conversations_lead_score'), 'conversations', ['lead_score'], unique=False)
    op.create_index(op.f('ix_conversations_lead_status'), 'conversations', ['lead_status'], unique=False)
    op.create_index(op.f('ix_conversations_participant_instagram_id'), 'conversations', ['participant_instagram_id'], unique=False)
    op.create_index(op.f('ix_conversations_participant_username'), 'conversations', ['participant_username'], unique=False)
    op.create_index(op.f('ix_conversations_thread_id'), 'conversations', ['thread_id'], unique=False)
    op.create_index(op.f('ix_conversations_updated_at'), 'conversations', ['updated_at'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('instagram_message_id', sa.String(length=100), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('sender_instagram_id', sa.String(length=100), nullable=False),
    sa.Column('sender_username', sa.String(length=255), nullable=True),
    sa.Column('is_from_me', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_spam', sa.Boolean(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('is_auto_replied', sa.Boolean(), nullable=False),
    sa.Column('auto_reply_text', sa.Text(), nullable=True),
    sa.Column('auto_reply_trigger', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'instagram_message_id', name='uq_message_instagram')
    )
    op.create_index('idx_message_conv_timestamp', 'messages', ['conversation_id', 'timestamp'], unique=False)
    op.create_index('idx_message_sender', 'messages', ['sender_instagram_id', 'timestamp'], unique=False)
    op.create_index('idx_message_unread', 'messages', ['conversation_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_deleted_at'), 'messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_messages_instagram_message_id'), 'messages', ['instagram_message_id'], unique=False)
    op.create_index(op.f('ix_messages_is_deleted'), 'messages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_messages_is_from_me'), 'messages', ['is_from_me'], unique=False)
    op.create_index(op.f('ix_messages_is_read'), 'messages', ['is_read'], unique=False)
    op.create_index(op.f('ix_messages_is_spam'), 'messages', ['is_spam'], unique=False)
    op.create_index(op.f('ix_messages_message_type'), 'messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_messages_read_at'), 'messages', ['read_at'], unique=False)
    op.create_index(op.f('ix_messages_sender_instagram_id'), 'messages', ['sender_instagram_id'], unique=False)
    op.create_index(op.f('ix_messages_sentiment_score'), 'messages', ['sentiment_score'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_messages_updated_at'), 'messages', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_updated_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_sentiment_score'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_instagram_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_read_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_spam'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_read'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_from_me'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_deleted'), table_name='messages')
    op.drop_index(op.f('ix_messages_instagram_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_deleted_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('idx_message_unread', table_name='messages')
    op.drop_index('idx_message_sender', table_name='messages')
    op.drop_index('idx_message_conv_timestamp', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_updated_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_thread_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_participant_username'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_participant_instagram_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_lead_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_lead_score'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_lead_priority'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_lead_assigned_to'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_is_spam'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_is_deleted'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_is_archived'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_instagram_account_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_deleted_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_index('idx_conv_last_message', table_name='conversations')
    op.drop_index('idx_conv_assigned_priority', table_name='conversations')
    op.drop_index('idx_conv_account_status', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_updated_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.drop_index(op.f('ix_comments_sentiment_score'), table_name='comments')
    op.drop_index(op.f('ix_comments_parent_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_is_spam'), table_name='comments')
    op.drop_index(op.f('ix_comments_is_reply'), table_name='comments')
    op.drop_index(op.f('ix_comments_is_hidden'), table_name='comments')
    op.drop_index(op.f('ix_comments_is_deleted'), table_name='comments')
    op.drop_index(op.f('ix_comments_instagram_comment_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_instagram_account_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_deleted_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_business_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_username'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_instagram_id'), table_name='comments')
    op.drop_index('idx_comment_timestamp', table_name='comments')
    op.drop_index('idx_comment_spam', table_name='comments')
    op.drop_index('idx_comment_instagram_parent', table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_instagram_accounts_username'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_updated_at'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_token_expires_at'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_last_synced_at'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_last_activity_at'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_is_deleted'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_is_connected'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_is_business'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_is_active'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_instagram_user_id'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_deleted_at'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_created_at'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_business_profile_id'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_business_id'), table_name='instagram_accounts')
    op.drop_index('idx_ig_account_username', table_name='instagram_accounts')
    op.drop_index('idx_ig_account_business_active', table_name='instagram_accounts')
    op.drop_table('instagram_accounts')
    op.drop_index(op.f('ix_resources_updated_at'), table_name='resources')
    op.drop_index(op.f('ix_resources_title'), table_name='resources')
    op.drop_index(op.f('ix_resources_slug'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_published_at'), table_name='resources')
    op.drop_index(op.f('ix_resources_is_published'), table_name='resources')
    op.drop_index(op.f('ix_resources_is_premium'), table_name='resources')
    op.drop_index(op.f('ix_resources_is_featured'), table_name='resources')
    op.drop_index(op.f('ix_resources_is_deleted'), table_name='resources')
    op.drop_index(op.f('ix_resources_deleted_at'), table_name='resources')
    op.drop_index(op.f('ix_resources_created_at'), table_name='resources')
    op.drop_index(op.f('ix_resources_category'), table_name='resources')
    op.drop_index(op.f('ix_resources_business_id'), table_name='resources')
    op.drop_index('idx_resource_type_published', table_name='resources')
    op.drop_index('idx_resource_featured', table_name='resources')
    op.drop_index('idx_resource_business_published', table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_updated_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_format'), table_name='reports')
    op.drop_index(op.f('ix_reports_next_run_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_name'), table_name='reports')
    op.drop_index(op.f('ix_reports_is_scheduled'), table_name='reports')
    op.drop_index(op.f('ix_reports_is_deleted'), table_name='reports')
    op.drop_index(op.f('ix_reports_deleted_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_date_range_start'), table_name='reports')
    op.drop_index(op.f('ix_reports_date_range_end'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_completed_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_business_id'), table_name='reports')
    op.drop_index('idx_report_status_date', table_name='reports')
    op.drop_index('idx_report_scheduled_next', table_name='reports')
    op.drop_index('idx_report_date_range', table_name='reports')
    op.drop_index('idx_report_business_type', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_leads_updated_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_source_type'), table_name='leads')
    op.drop_index(op.f('ix_leads_source_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_priority'), table_name='leads')
    op.drop_index(op.f('ix_leads_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_last_conversation_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_is_deleted'), table_name='leads')
    op.drop_index(op.f('ix_leads_instagram_username'), table_name='leads')
    op.drop_index(op.f('ix_leads_instagram_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_funnel_stage'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_deleted_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_converted_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_business_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to'), table_name='leads')
    op.drop_index('idx_lead_priority_score', table_name='leads')
    op.drop_index('idx_lead_instagram', table_name='leads')
    op.drop_index('idx_lead_conversion', table_name='leads')
    op.drop_index('idx_lead_business_status', table_name='leads')
    op.drop_index('idx_lead_assigned_status', table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_business_profiles_updated_at'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_token_expires_at'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_platform_username'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_platform_user_id'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_platform'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_last_synced_at'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_is_connected'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_is_active'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_created_at'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_business_id'), table_name='business_profiles')
    op.drop_index('idx_bp_platform_connected', table_name='business_profiles')
    op.drop_index('idx_bp_business_platform', table_name='business_profiles')
    op.drop_table('business_profiles')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_last_active_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_is_active'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_ip_address'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_created_at'), table_name='user_sessions')
    op.drop_index('idx_session_user_active', table_name='user_sessions')
    op.drop_index('idx_session_expires', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_subscriptions_updated_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_trial_end'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_next_payment_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_last_payment_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_external_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_external_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_created_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_canceled_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_cancel_at_period_end'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_billing_period_start'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_billing_period_end'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_billing_cycle'), table_name='subscriptions')
    op.drop_index('idx_sub_status_period', table_name='subscriptions')
    op.drop_index('idx_sub_org_status', table_name='subscriptions')
    op.drop_index('idx_sub_next_payment', table_name='subscriptions')
    op.drop_index('idx_sub_external', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_settings_updated_at'), table_name='settings')
    op.drop_index(op.f('ix_settings_organization_id'), table_name='settings')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_created_at'), table_name='settings')
    op.drop_index(op.f('ix_settings_category'), table_name='settings')
    op.drop_index('idx_setting_category', table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_family'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_last_used_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_used'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_ip_address'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index('idx_user_active_tokens', table_name='refresh_tokens')
    op.drop_index('idx_token_family_created', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_is_used'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_is_revoked'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_otp_codes_user_id'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_purpose'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_is_verified'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_is_used'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_expires_at'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_code_type'), table_name='otp_codes')
    op.drop_index('idx_otp_user_purpose_active', table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_updated_at'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_role'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_is_active'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_created_at'), table_name='organization_members')
    op.drop_index('idx_org_member_user_active', table_name='organization_members')
    op.drop_index('idx_org_member_org_role', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_updated_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_resource_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_resource_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_priority'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_expires_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_email_sent'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_deleted_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('idx_notification_user_read', table_name='notifications')
    op.drop_index('idx_notification_user_priority', table_name='notifications')
    op.drop_index('idx_notification_unread_count', table_name='notifications')
    op.drop_index('idx_notification_type_created', table_name='notifications')
    op.drop_index('idx_notification_resource', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_login_attempts_user_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_successful'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_index('idx_ip_attempted', table_name='login_attempts')
    op.drop_index('idx_email_attempted', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_email_verifications_user_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_token_hash'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_is_verified'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_expires_at'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_businesses_updated_at'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_slug'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_owner_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_organization_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_is_verified'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_is_deleted'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_is_active'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_industry'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_email'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_deleted_at'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_created_at'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_country'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_city'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_business_type'), table_name='businesses')
    op.drop_index('idx_business_type_active', table_name='businesses')
    op.drop_index('idx_business_org_active', table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_updated_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_action_created', table_name='audit_logs')
    op.drop_index('idx_audit_status_created', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_org_category', table_name='audit_logs')
    op.drop_index('idx_audit_ip_created', table_name='audit_logs')
    op.drop_index('idx_audit_action_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_updated_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_last_used_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_revoked'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_expires_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_index('idx_api_key_user_active', table_name='api_keys')
    op.drop_index('idx_api_key_org_active', table_name='api_keys')
    op.drop_index('idx_api_key_expires', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_last_login_at'), table_name='users')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_superuser'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email_verified_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index('idx_user_organization', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_updated_at'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_plan_expires_at'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_plan'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_owner_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_suspended'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_deleted'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_active'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_deleted_at'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.drop_index('idx_org_slug_active', table_name='organizations')
    op.drop_index('idx_org_plan_active', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
